---
driver:
  name: dokken
  privileged: true
  # chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken

# verifier:
#  name: inspec

platforms:
- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release

- name: centos-6.8
  driver:
    image: centos:6.8
    platform: rhel
    intermediate_instructions:
      - RUN yum install -y net-tools initscripts which

- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /usr/lib/systemd/systemd
    platform: rhel
    intermediate_instructions:
      - RUN yum install -y net-tools initscripts systemd-sysv which lsof

- name: amazonlinux
  driver:
    image: amazonlinux:2017.03
    platform: amazon
    intermediate_instructions:
      - RUN yum install -y net-tools initscripts which
    pid_one_command: /sbin/init

suites:
  - name: default12
    driver:
      chef_version: 12.21.3
    run_list:
      - recipe[filebeat::default]
      - recipe[filebeat_test::default]
    attributes:
      filebeat:
        prospectors:
          secure_logs:
            filebeat:
              prospectors:
              - paths:
                - /var/log/secure
                type: log
                fields:
                  type: secure_logs
          syslog_logs:
            filebeat:
              prospectors:
              - paths:
                - /var/log/syslog
                type: log
                fields:
                  type: syslog_logs
          messages_log:
            filebeat:
              prospectors:
              - paths:
                - /var/log/messages
                type: log
                fields:
                  type: messages_log
          extra_log:
            filebeat:
              prospectors:
              - paths:
                - /var/log/*.log
                type: log
                fields:
                  type: extra_log
                exclude_files:
                - /var/log/messages
                - /var/log/syslog
                - /var/log/secure
        config:
          output:
            elasticsearch:
              hosts: ["127.0.0.1:9200"]

  - name: default13
    driver:
      chef_version: 13.2.20
    run_list:
      - recipe[filebeat::default]
      - recipe[filebeat_test::default]
    attributes:
      filebeat:
        prospectors:
          secure_logs:
            filebeat:
              prospectors:
              - paths:
                - /var/log/secure
                type: log
                fields:
                  type: secure_logs
          syslog_logs:
            filebeat:
              prospectors:
              - paths:
                - /var/log/syslog
                type: log
                fields:
                  type: syslog_logs
          messages_log:
            filebeat:
              prospectors:
              - paths:
                - /var/log/messages
                type: log
                fields:
                  type: messages_log
          extra_log:
            filebeat:
              prospectors:
              - paths:
                - /var/log/*.log
                type: log
                fields:
                  type: extra_log
                exclude_files:
                - /var/log/messages
                - /var/log/syslog
                - /var/log/secure
        config:
          output:
            elasticsearch:
              hosts: ["127.0.0.1:9200"]
